### PR TITLE
Sprint 03/10

### PR DESCRIPTION
**Pull request by jpms2**
Tool now recognizes link_to expressions

---

This change is [Reviewable](https://reviewable.io/reviews/pauloborba/tan/2)

### CODE REVIEW

**Comment by pauloborba** [comment]
Reviewed 24 of 34 files at r1.
Review status: 24 of 34 files reviewed at latest revision, 15 unresolved discussions.

---

_[Gemfile.lock, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUMcWNbpeAiQ0IDZRqT:-KUMcWNbpeAiQ0IDZRqU:b-5t3zuo) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Gemfile.lock#L1)):_

> ``` Ruby
> GEM
> ```

precisa mesmo subir esse arquivo?

---

_[ErbFileAnalyser/Erb_tags_remover.rb, line 6 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNBPOIaV6NnhOdoCo3:-KUNBPOIaV6NnhOdoCo4:b-shqco) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Erb_tags_remover.rb#L6)):_

> ``` Ruby
>     matchdata = text.scan(/(?<=\<%)(.*?)(?=\%>)/)
>     matchdata.each do |tagged_code|
>       tagged_code.each do |code_with_tags|
> ```

tagged_code e code_with_tags parecem representar a mesma coisa. pode melhorar os nomes das variáveis... matchdata também é bem genérico... é uma coleção de matched code?

---

_[ErbFileAnalyser/Erb_tags_remover.rb, line 7 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNAobpmJ7gFvzWoxlm:-KUNAobpmJ7gFvzWoxln:b-gj0pqe) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Erb_tags_remover.rb#L7)):_

> ``` Ruby
>     matchdata.each do |tagged_code|
>       tagged_code.each do |code_with_tags|
>         #removing opening tag
> ```

ao invés do comentário, extrai um método com nome apropriado...

---

_[ErbFileAnalyser/Grab_controller_from_erb_file.rb, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNCf6uobCKmvRVZH0q:-KUNCf6uobCKmvRVZH0r:b-4s6uwn) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Grab_controller_from_erb_file.rb#L1)):_

> ``` Ruby
> class ControllerGrabber
> ```

seria legal colocar um pequeno comentário no início de cada classe, explicando de forma geral o propósito dela. e anexar no readme um diagrama da arquitetura.

---

_[ErbFileAnalyser/Grab_controller_from_erb_file.rb, line 15 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNCwtM88x9nGwX4B_W:-KUNCwtNNdcTtlUmrgiJ:bijka9e) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Grab_controller_from_erb_file.rb#L15)):_

> ``` Ruby
>     code = ErbTagsRemover.new.remove_erb_tags(file_text)
>     parsed_code = Ruby_parser.new.parse_code(code)
>     output_array = Method_controller_visitor.new.find_controllers(parsed_code)
> ```

você está chamando só invocações de ações do controller ou está pegando também links para outras páginas e coisas do tipo?

---

_[ErbFileAnalyser/output.txt, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNFLaO2gTJDB6889CB:-KUNFLaO2gTJDB6889CC:b-iin8mu) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/output.txt#L1)):_

> ```
> [name: Show, type: @otml_file]
> ```

precisa mesmo subir esse arquivo?

---

_[samples/sample14.html.erb, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNDEus_OWF2IucE9zQ:-KUNDEus_OWF2IucE9zR:b-thbvl0) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/samples/sample14.html.erb#L1)):_

> ``` erb
> <h1>New otrunk_import</h1>
> ```

esses são arquivos originais de arquivos de projetos existentes, certo? você não simplificou os arquivos, certo?

---

_[samples/sample_expected_answer.txt, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNDtWt1ridg4z1v4jV:-KUNDtWt1ridg4z1v4jW:bkpyrx) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/samples/sample_expected_answer.txt#L1)):_

> ```
> [name: Show, type: @otml_file]
> ```

resposta esperada de que arquivo de entrada?

---

_[spec/ErbFileAnalyser/Erb_tags_remover_spec.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNHqQIt7DKivjMzWsF:-KUNHqQIt7DKivjMzWsG:b-uomtcp) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/spec/ErbFileAnalyser/Erb_tags_remover_spec.rb#L5)):_

> ``` Ruby
> require_relative '../../Util/ruby_parser'
> 
> describe 'Get ruby code' do
> ```

vamos combinar uma melhor descrição via chat

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNH8qeFZkZjXtjuFTf:-KUNH8qeFZkZjXtjuFTg:b-wvec6c) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L11)):_

> ``` Ruby
>       path = /.*(?=\/)/.match(hard_path).to_s
>       path = /.*(?=\/)/.match(path).to_s
>       path = /.*(?=\/)/.match(path).to_s
> ```

merece extrair um método, com nome apropriado, para esse código acima

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 17 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNGrq9VsYQZ6f9dsEb:-KUNGrq9VsYQZ6f9dsEc:b-70ivqh) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L17)):_

> ``` Ruby
>       controller_grabber.grab_controllers("#{path}/samples/sample1.html.erb")
>       file_manager = File_manager.new
>       answer_string = file_manager.read_file("#{path}/samples/sample_expected_answer.txt").gsub(/\s+/, "")
> ```

melhor adotar logo uma solução para quando formos comparar várias entradas com várias saídas. nessa sprint deveria pelo menos fazer isso para dois arquivos

---

_[Util/ruby_parser.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNF0K8EZkqKFJDmdxX:-KUNF0K8EZkqKFJDmdxY:bce5dhq) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Util/ruby_parser.rb#L5)):_

> ``` Ruby
> 
> class Ruby_parser
>  Parser::Builders::Default.emit_lambda = true # opt-in to most recent AST format
> ```

indentação precisa de ajuste?

---

_[Util/ruby_parser.rb, line 8 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNFCMRVyWoHqnMWzNF:-KUNFCMRVyWoHqnMWzNG:b869ami) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Util/ruby_parser.rb#L8)):_

> ``` Ruby
> 
>   def parse_code(code)
>     p Parser::CurrentRuby.parse(code)
> ```

não entendi. o que é esse p aí?

---

_[Visitors/method_controller_visitor.rb, line 6 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNHyanYFBTwNEjIeqC:-KUNHyanYFBTwNEjIeqD:bswg79a) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Visitors/method_controller_visitor.rb#L6)):_

> ``` Ruby
> 
>   $output_array = []
>   def do_nothing
> ```

esquisito!

---

_[Visitors/method_controller_visitor.rb, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNIQw25PyNAC6WwbFQ:-KUNIQw25PyNAC6WwbFR:b-wqs26d) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Visitors/method_controller_visitor.rb#L12)):_

> ``` Ruby
>       link_to = :link_to
>       str = :str
>       ivar = :ivar
> ```

eu estava esperando um visitor, mas isso não é exatamente um. não faz sentido o visitor pois todos os nós são da mesma classe?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by jpms2** [comment]
Review status: 24 of 34 files reviewed at latest revision, 15 unresolved discussions.

---

_[Gemfile.lock, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUMcWNbpeAiQ0IDZRqT:-KUOXOL7ER9fzDfMU9Bz:bsooixw) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Gemfile.lock#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> precisa mesmo subir esse arquivo?
> </details>
> Precisei dele para rodar o projeto no travis, então creio que seja necessário para que alguém que baixe a ferramenta

---

_[ErbFileAnalyser/Grab_controller_from_erb_file.rb, line 15 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNCwtM88x9nGwX4B_W:-KUOY-EDf6_hjhmTHPtz:b-2czc56) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Grab_controller_from_erb_file.rb#L15)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> você está chamando só invocações de ações do controller ou está pegando também links para outras páginas e coisas do tipo?
> </details>
> Estou pegando tanto chamadas de método quanto as variáveis de instância(links)

---

_[ErbFileAnalyser/output.txt, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNFLaO2gTJDB6889CB:-KUOYDYHvyy0q26Dhfoe:b-q2qotz) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/output.txt#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> precisa mesmo subir esse arquivo?
> </details>
> Precisei subir para que um teste passasse no travis, vou procurar uma maneira de rodar o programa antes de testar

---

_[samples/sample14.html.erb, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNDEus_OWF2IucE9zQ:-KUOYRcUWelR2eAYmjQa:b-5betk) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/samples/sample14.html.erb#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> esses são arquivos originais de arquivos de projetos existentes, certo? você não simplificou os arquivos, certo?
> </details>
> Nenhum foi simplificado, aqui nesse link o senhor pode ter acesso ao código que eu peguei
> https://github.com/concord-consortium/rigse/blob/master/app/views/otrunk_example/otrunk_view_entries/new.html.erb

---

_[Util/ruby_parser.rb, line 8 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNFCMRVyWoHqnMWzNF:-KUOZetAGI0m5qBWVNpj:b-rnlb9l) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Util/ruby_parser.rb#L8)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> não entendi. o que é esse p aí?
> </details>
> Esse é o modo que a documentação do parser pede para chamar o método
> https://github.com/whitequark/parser

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by pauloborba** [comment]
Reviewed 2 of 35 files at r1, 9 of 13 files at r2.
Review status: 32 of 36 files reviewed at latest revision, 11 unresolved discussions.

---

_[README.md, line 3 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3OuuUTFr-r_s8k2m:-KUc3OuuUTFr-r_s8k2n:b-xm8ple) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L3)):_

> ``` Markdown
> # tan
> 
> Tool made for finding possible controllers inside .erb views.
> ```

controllers -> controller calls 

---

_[README.md, line 7 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3hqIHog2n--SxiBe:-KUc3hqIHog2n--SxiBf:bry01tn) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L7)):_

> ``` Markdown
> 
> Run it by running: (don't forget to bundle install!)
>   ruby Grab_controller_from_erb_file.rb
> ```

recebe parâmetros? como o nome do arquivo a ser processado? onde colocar a saída?

---

_[README.md, line 11 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3qfC9H7gKU1ER9nN:-KUc3qfC9H7gKU1ER9nO:b4cao11) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L11)):_

> ``` Markdown
> Architecture:
> 
>   [Grab_controller_from_erb_file.rb](https://github.com/jpms2/tan/blob/master/ErbFileAnalyser/Grab_controller_from_erb_file.rb) is the main file, receiving all methods and calling them together to create an output folder on the    directory.
> ```

que directory?

receiving all methods and calling them together -> invoking methods from the other classes

---

_[README.md, line 13 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc4DBpYe8lDXKrekbx:-KUc4DBpYe8lDXKrekby:bjemh0l) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L13)):_

> method calls that might be made by a controller 
> calls to controller methods, and returns an an output_model array

---

_[ErbFileAnalyser/Grab_controller_from_erb_file.rb, line 23 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc0xfspalezHiQ7IFD:-KUc0xfspalezHiQ7IFE:b-kyf89z) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/ErbFileAnalyser/Grab_controller_from_erb_file.rb#L23)):_

> "#{get_relative_path}/outputs/#{file_manager.get_file_name(file_path)}_output"
> extraindo isso para uma variável local não fica melhor?

---

_[spec/ErbFileAnalyser/Erb_tags_remover_spec.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNHqQIt7DKivjMzWsF:-KUc9WnA0VR0-j2XZfha:b-7lyy5g) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/spec/ErbFileAnalyser/Erb_tags_remover_spec.rb#L5)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> vamos combinar uma melhor descrição via chat
> </details>
> isso daqui deve ser assim: describe 'Erb tags removal function' 
>                                                      it 'does not break for the files in the samples directory'
> o context não faz sentido aqui. se tiver dúvida ou achar que não está legal, me procura no slack

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 5 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUcAGpNopYxjDJhXmFs:-KUcAGpNopYxjDJhXmFt:bx9ajz5) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L5)):_

> ``` Ruby
> require_relative '../../ErbFileAnalyser/Grab_controller_from_erb_file'
> 
> describe "Get actions calls" do
> ```

esse daqui deve ser assim: describe 'Extraction of dependencies in erb files, including calls to controller actions' 
                                                     it 'does produce correct mappings for the files in the samples directory'

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 13 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUcBXeTj2Bl5THNjPGa:-KUcBXeTj2Bl5THNjPGb:bgopj4s) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L13)):_

> ``` Ruby
>       $passed = true
>       file_manager = File_manager.new
>       while i < 4 do
> ```

testando só para 4 arquivos?

---

_[Visitors/method_controller_visitor.rb, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNIQw25PyNAC6WwbFQ:-KUc1rrbJONIF34Bp0lE:b-k4a05g) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Visitors/method_controller_visitor.rb#L12)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> eu estava esperando um visitor, mas isso não é exatamente um. não faz sentido o visitor pois todos os nós são da mesma classe?
> </details>
> melhor mudar o nome da classe e pacote, já que não é um visitor mesmo

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by pauloborba** [comment]
Reviewed 4 of 13 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by jpms2** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[README.md, line 3 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3OuuUTFr-r_s8k2m:-KUsYk2zgwUMlVEUvGyV:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L3)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> controllers -> controller calls 
> </details>
> Done.

---

_[README.md, line 7 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3hqIHog2n--SxiBe:-KUsYjpAeJ3p2cL048Xu:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L7)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> recebe parâmetros? como o nome do arquivo a ser processado? onde colocar a saída?
> </details>
> Done.

---

_[README.md, line 11 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc3qfC9H7gKU1ER9nN:-KUsYj5nRKv5GOvtA7gI:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L11)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> que directory?
> 
> receiving all methods and calling them together -> invoking methods from the other classes
> </details>
> Done.

---

_[README.md, line 13 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc4DBpYe8lDXKrekbx:-KUsYiNfq8n3Kz61Tw7R:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/README.md#L13)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> > method calls that might be made by a controller 
> > calls to controller methods, and returns an an output_model array
> > </details>
> > Done.

---

_[ErbFileAnalyser/Erb_tags_remover.rb, line 6 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNBPOIaV6NnhOdoCo3:-KUs8iurOGq3xF_p1g0_:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Erb_tags_remover.rb#L6)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> tagged_code e code_with_tags parecem representar a mesma coisa. pode melhorar os nomes das variáveis... matchdata também é bem genérico... é uma coleção de matched code?
> </details>
> Done.

---

_[ErbFileAnalyser/Erb_tags_remover.rb, line 7 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNAobpmJ7gFvzWoxlm:-KUs8hBjQVAMRBvDxkf3:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/ErbFileAnalyser/Erb_tags_remover.rb#L7)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> ao invés do comentário, extrai um método com nome apropriado...
> </details>
> Done.

---

_[ErbFileAnalyser/Grab_controller_from_erb_file.rb, line 23 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUc0xfspalezHiQ7IFD:-KUs8kwm54s_EVUDrZQe:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/ErbFileAnalyser/Grab_controller_from_erb_file.rb#L23)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> > "#{get_relative_path}/outputs/#{file_manager.get_file_name(file_path)}_output"
> > extraindo isso para uma variável local não fica melhor?
> > </details>
> > Done.

---

_[samples/sample1_expected_answer.txt, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNDtWt1ridg4z1v4jV:-KUsYr1VWeLrG-dXR6cZ:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/samples/sample1_expected_answer.txt#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> resposta esperada de que arquivo de entrada?
> </details>
> Done.

---

_[spec/ErbFileAnalyser/Erb_tags_remover_spec.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNHqQIt7DKivjMzWsF:-KUs8nPf4ILw7ChZuVDa:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/spec/ErbFileAnalyser/Erb_tags_remover_spec.rb#L5)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> isso daqui deve ser assim: describe 'Erb tags removal function' 
>                                                      it 'does not break for the files in the samples directory'
> o context não faz sentido aqui. se tiver dúvida ou achar que não está legal, me procura no slack
> </details>
> Done.

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 5 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUcAGpNopYxjDJhXmFs:-KUs8o1Ex9oPSS4T5VyH:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L5)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> esse daqui deve ser assim: describe 'Extraction of dependencies in erb files, including calls to controller actions' 
>                                                      it 'does produce correct mappings for the files in the samples directory'
> </details>
> Done.

---

_[spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb, line 13 at r2](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUcBXeTj2Bl5THNjPGa:-KUs9BuLNnylu-chnbQv:bqlhzlm) ([raw file](https://github.com/pauloborba/tan/blob/18b058a8a76bd09068be5b8aaeb68bfd3862fbb7/spec/ErbFileAnalyser/Grab_controller_from_erb_file_spec.rb#L13)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> testando só para 4 arquivos?
> </details>
> São os arquivos de saída que Thaís entregou

---

_[Visitors/method_controller_visitor.rb, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/tan/2#-KUNIQw25PyNAC6WwbFQ:-KUs9GxqLuqqauU9-ODc:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/02c8719c686e9a1bb389cf7f788da4f318822b02/Visitors/method_controller_visitor.rb#L12)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> melhor mudar o nome da classe e pacote, já que não é um visitor mesmo
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by pauloborba** [comment]
Reviewed 1 of 13 files at r2, 15 of 16 files at r3.
Review status: 37 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

_[ErbFileAnalyser/find_controller_calls.rb, line 48 at r3](https://reviewable.io:443/reviews/pauloborba/tan/2#-KVFkp9FtNR-_SmtyY_R:-KVFkp9FtNR-_SmtyY_S:b-du1jvb) ([raw file](https://github.com/pauloborba/tan/blob/afc6827beaba8ddfc1d08fe44f38bab3e5258a2e/ErbFileAnalyser/find_controller_calls.rb#L48)):_

> ``` Ruby
> 
> end
> ```

poderia melhorar bastante a legibilidade, extraindo mais variáveis locais e métodos. melhor discutir pessoalmente para a próxima iteração. 

---

_[Util/transform_into.rb, line 2 at r3](https://reviewable.io:443/reviews/pauloborba/tan/2#-KVFhj0Ms5O8Qj4ZI_v6:-KVFhj0Ms5O8Qj4ZI_v7:bbyk56q) ([raw file](https://github.com/pauloborba/tan/blob/afc6827beaba8ddfc1d08fe44f38bab3e5258a2e/Util/transform_into.rb#L2)):_

> ``` Ruby
> require 'active_support/inflector'
> ```

faltou comentário geral no início da classe

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Comment by pauloborba** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/2)_

**Pull request merged**
