### PR TITLE
Second iteration pull request

### PR DESCRIPTION
**Pull request by jpms2**
This change is [Reviewable](https://reviewable.io/reviews/pauloborba/tan/3)

### CODE REVIEW

**Comment by pauloborba** [comment]
Reviewed 33 of 41 files at r1.
Review status: 28 of 35 files reviewed at latest revision, 16 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT25nUeNCzzixGULSy:-KZT25nUeNCzzixGULSz:br7ss4k) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/README.md#L3)):*
> ```Markdown
> # tan
> 
> Tool made for finding possible controller calls inside .erb views.
> ```

descrições e nomes deveriam ser atualizados para considerar erb e haml

---

*[lib/task_analyser.rb, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT2WlTb2ZAsXPfObvG:-KZT2WlTb2ZAsXPfObvH:b8k16si) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/task_analyser.rb#L11)):*
> ```Ruby
>         puts ControllerGrabber.new.grab_controllers(file_path)
>       when 'haml'
>         puts Grab_controller_from_haml_file.new.controller_grabber(file_path)
> ```

merece um renaming das classes e métodos. deveria ser ErbControllerExtractor e HamlControllerExtractor. e os métodos deveriam ter o mesmo nome

---

*[lib/task_analyser.rb, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT2S4fgSfLZyZ8ZTbl:-KZT2S4fgSfLZyZ8ZTbm:b-reutjr) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/task_analyser.rb#L13)):*
> ```Ruby
>         puts Grab_controller_from_haml_file.new.controller_grabber(file_path)
>       else
> ```

deveria dar uma mensagem de erro, dizendo que só suporta .erb e .haml

---

*[lib/Analyser/find_controller_calls.rb, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTBGNuTDEHGJ-Mwo_M:-KZTBGNuTDEHGJ-Mwo_N:b-2wemmx) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L1)):*
> ```Ruby
> #Visits parse tree looking for calls to controllers, when found, insert them on an array
> ```

que parse tree? de erb ou haml?

---

*[lib/Analyser/find_controller_calls.rb, line 56 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTB_azUeE8UgJ_tRiF:-KZTB_azUeE8UgJ_tRiG:btondr0) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L56)):*
> ```Ruby
>       $output_array
>     else
>       $output_array
> ```

se retorna a mesma coisa nao precisaria do if! o que é output_array? variável global?

---

*[lib/Analyser/find_controller_calls.rb, line 73 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTCKJknE4xTR2DuuI_:-KZTCKJknE4xTR2DuuIa:burrssn) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L73)):*
> ```Ruby
>   controller_name = ''
>   method_name = code.children[1]
>   if method_name == $link_to
> ```

achando meio amarrado. não é bem um visitor. os nós da árvore são todos de uma mesma classe? ou há uma hierarquia de classes para os nós?

---

*[lib/Analyser/find_controller_calls.rb, line 365 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTCgxchdY-Dn4GC60Z:-KZTCgxduj8gvG5D9oA9:bjoxynw) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L365)):*
> ```Ruby
> 
> def is_still_a_node(code)
>   if code.is_a?(Parser::AST::Node)
> ```

bastava a expressão do if, eliminando o if

---

*[lib/HamlFileAnalyser/Haml_end_adder.rb, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTD6tZF_zCjVicNUQG:-KZTD6tZF_zCjVicNUQH:boq5d4v) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_end_adder.rb#L11)):*
> ```Ruby
>   end
> 
>   def add_ends(file_path)
> ```

precisa de um bom refatoramento!

---

*[lib/HamlFileAnalyser/Haml_end_adder.rb, line 72 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDCJBx6ecSem0_IuP:-KZTDCJBx6ecSem0_IuQ:b-7p18x3) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_end_adder.rb#L72)):*
> ```Ruby
>   end
> 
>   def find_end_position(next_indentations_values,line_num, indentation_value)
> ```

idem!

---

*[lib/HamlFileAnalyser/Haml_parser.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDTtzr4syvrVtZfnS:-KZTDTtzr4syvrVtZfnT:b-gh8by) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_parser.rb#L5)):*
> ```Ruby
> class Haml_parser
> 
>   def parse(text)
> ```

precisa de refactoring!

---

*[lib/Util/transform_into.rb, line 3 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDj4kTjoGGOU-FwJD:-KZTDj4kTjoGGOU-FwJE:bi81m3x) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Util/transform_into.rb#L3)):*
> ```Ruby
> require 'active_support/inflector'
> 
> class Transform_into
> ```

falta documentação! revisão todos os pontos do pinned item do slack

---

*[lib/Util/transform_into.rb, line 7 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDetKfJ658nejXIuw:-KZTDetKfJ658nejXIux:bn9xvi2) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Util/transform_into.rb#L7)):*
> ```Ruby
>   def self.var_into_controller(var)
>     if var == ''
> ```

não faz nada?! esquisito 

---

*[samples/sample22.html.erb, line 25 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTAqR5Hxu4bGt067GW:-KZTAqR5Hxu4bGt067GX:bnznfpq) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/samples/sample22.html.erb#L25)):*
> ```erb
>     <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
>   <% end -%>
> <% end -%>
> ```

não tem expected answer? rever isso para todos os samples

---

*[samples/sample4.html.haml, line 25 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTAYZ-PGWZPu_FEiTK:-KZTAYZ-PGWZPu_FEiTL:b-9o0f71) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/samples/sample4.html.haml#L25)):*
> ```Haml
>       });
>     });
>   });
> ```

não tem a expected answer para todos os exemplos de entrada?

---

*[spec/HamlFileAnalyser/Grab_controller_from_haml_file_spec.rb, line 10 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTE8RL6eMI3TV7NUqL:-KZTE8RL6eMI3TV7NUqM:brghpsp) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/spec/HamlFileAnalyser/Grab_controller_from_haml_file_spec.rb#L10)):*
> ```Ruby
>     $passed = true
>     file_manager = File_manager.new
>     while i < 4 do
> ```

devia generalizar. rodar para todos os arquivos de sample disponíveis no diretório

---

*[spec/HamlFileAnalyser/Haml_parser_spec.rb, line 7 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTEOupk2fESjo_dfaK:-KZTEOuqHDVOCo5o75bd:b-jogh9w) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/spec/HamlFileAnalyser/Haml_parser_spec.rb#L7)):*
> ```Ruby
> describe 'Haml parser function' do
> 
>   it 'does not break for the files in the samples directory' do
> ```

melhor dois diretórios? um com todos arquivos desse teste, e outro com os arquivos de entrada/saída esperada

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/3)*

**Comment by jpms2** [comment]
Review status: 28 of 35 files reviewed at latest revision, 16 unresolved discussions.

---

*[README.md, line 3 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT25nUeNCzzixGULSy:-KZX6JsLshn1S0Fd9_M7:b-htbhc4) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/README.md#L3)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

descrições e nomes deveriam ser atualizados para considerar erb e haml
</blockquote></details>

Acabei fazendo essa mudança no branch errado! Vou corrigir

---

*[lib/task_analyser.rb, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT2WlTb2ZAsXPfObvG:-KZXqtbTh6k5LdQB3Dbf:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/task_analyser.rb#L11)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

merece um renaming das classes e métodos. deveria ser ErbControllerExtractor e HamlControllerExtractor. e os métodos deveriam ter o mesmo nome
</blockquote></details>

Done.

---

*[lib/task_analyser.rb, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZT2S4fgSfLZyZ8ZTbl:-KZXqslqp_7ZFIuoHvZR:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/task_analyser.rb#L13)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

deveria dar uma mensagem de erro, dizendo que só suporta .erb e .haml
</blockquote></details>

Done.

---

*[lib/Analyser/find_controller_calls.rb, line 1 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTBGNuTDEHGJ-Mwo_M:-KZX9eVWBimoSUApliIM:bfxk4t8) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L1)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

que parse tree? de erb ou haml?
</blockquote></details>

Ambas, essa classe recebe código já tratado. Tanto o código erb quanto o haml usam ruby e html, logo, todas as chamadas a métodos, etc são feitas em ruby, essa classe só consegue ler código ruby e procurar as chamadas a outras classes, por isso antes de chamar essa classe eu chamo outras como haml_parser ou erb_tags_remover

---

*[lib/Analyser/find_controller_calls.rb, line 56 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTB_azUeE8UgJ_tRiF:-KZXFztVn9BOL6jIpyec:bv7uqi2) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L56)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

se retorna a mesma coisa nao precisaria do if! o que é output_array? variável global?
</blockquote></details>

Sim, é uma variável global, basicamente o array que contém todas as chamadas a controladores encontradas. Já corrigi, realmente passou batido

---

*[lib/Analyser/find_controller_calls.rb, line 73 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTCKJknE4xTR2DuuI_:-KZXHjm8b2Ehk0V-hZFk:bvov7u6) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L73)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

achando meio amarrado. não é bem um visitor. os nós da árvore são todos de uma mesma classe? ou há uma hierarquia de classes para os nós?
</blockquote></details>

Sim ,todos os nós são da mesma classe (node), por isso é feito dessa forma

---

*[lib/Analyser/find_controller_calls.rb, line 365 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTCgxchdY-Dn4GC60Z:-KZXqqA2BY7WvnHFjHdF:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Analyser/find_controller_calls.rb#L365)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

bastava a expressão do if, eliminando o if
</blockquote></details>

Done.

---

*[lib/HamlFileAnalyser/Haml_end_adder.rb, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTD6tZF_zCjVicNUQG:-KZXqp7h0ZX5J-aH2oUs:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_end_adder.rb#L11)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

precisa de um bom refatoramento!
</blockquote></details>

Done.

---

*[lib/HamlFileAnalyser/Haml_end_adder.rb, line 72 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDCJBx6ecSem0_IuP:-KZXhV25X2HfXhk6Pzel:b-m7jsub) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_end_adder.rb#L72)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

idem!
</blockquote></details>

O senhor pode dar uma ideia de onde começar a refatorar essa parte? Tentei dividir o método mas cada vez que criava um novo o número de parâmetros crescia muito

---

*[lib/HamlFileAnalyser/Haml_parser.rb, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDTtzr4syvrVtZfnS:-KZXqniKy6UxEkJJTSWp:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_parser.rb#L5)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

precisa de refactoring!
</blockquote></details>

Done.

---

*[lib/Util/transform_into.rb, line 3 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDj4kTjoGGOU-FwJD:-KZXqlC5DWQgFoneB01v:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Util/transform_into.rb#L3)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

falta documentação! revisão todos os pontos do pinned item do slack
</blockquote></details>

Done.

---

*[lib/Util/transform_into.rb, line 7 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDetKfJ658nejXIuw:-KZXqkBf2VpVJD_rSwqW:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/Util/transform_into.rb#L7)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não faz nada?! esquisito 
</blockquote></details>

Done.

---

*[samples/sample22.html.erb, line 25 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTAqR5Hxu4bGt067GW:-KZXqfD0H4PtkEOU-flI:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/samples/sample22.html.erb#L25)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não tem expected answer? rever isso para todos os samples
</blockquote></details>

Done.

---

*[samples/sample4.html.haml, line 25 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTAYZ-PGWZPu_FEiTK:-KZXqh1W5JSq6hkquoqm:b-896fix) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/samples/sample4.html.haml#L25)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não tem a expected answer para todos os exemplos de entrada?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/3)*

**Comment by pauloborba** [comment]
Reviewed 29 of 52 files at r2.
Review status: 45 of 63 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/HamlFileAnalyser/Haml_end_adder.rb, line 72 at r1](https://reviewable.io:443/reviews/pauloborba/tan/3#-KZTDCJBx6ecSem0_IuP:-KaclNpyFubdZzNktO6y:bpohml6) ([raw file](https://github.com/pauloborba/tan/blob/2f1b579d07bec71ae2fd4d514948ba9b22eb32ac/lib/HamlFileAnalyser/Haml_end_adder.rb#L72)):*
<details><summary><i>Previously, jpms2 (João Pedro de Medeiros Santos) wrote…</i></summary><blockquote>

O senhor pode dar uma ideia de onde começar a refatorar essa parte? Tentei dividir o método mas cada vez que criava um novo o número de parâmetros crescia muito
</blockquote></details>

por exemplo, esses 3 ifs seguidos deveria virar um único if, com uma condição definida em um método que seria chamado como condição do if. algumas das variáveis locais devem poder ser definidas nesse método, ao invés de passadas como parâmetro

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/3)*

**Comment by pauloborba** [comment]
Reviewed 2 of 46 files at r1, 23 of 52 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/tan/3)*

**Pull request merged**
